const data = {
  products: [
    {
      _id: "1",
      name: "Red PS4 Controller",
      category: "Game Controllers",
      image: "/images/p1.jpg",
      price: 55,
      countInStock: 10,
      brand: "Playstation",
      rating: 4.5,
      numReviews: 10,
      description: "Controller for the PS4",
    },
    {
      _id: "2",
      name: "Blue Xbox One X/S Controller",
      category: "Game Controllers",
      image: "/images/p2.jpg",
      price: 66,
      countInStock: 20,
      brand: "Xbox",
      rating: 4.0,
      numReviews: 10,
      description: "Controller for the Xbox One X/S",
    },
    {
      _id: "3",
      name: "Black Nintendo Switch Controller",
      category: "Game Controllers",
      image: "/images/p3.jpg",
      price: 65,
      countInStock: 0,
      brand: "Nintendo",
      rating: 4.8,
      numReviews: 17,
      description: "Controller for the Nintendo Switch",
    },
    {
      _id: "4",
      name: "Elite Black Xbox One X/S Controller",
      category: "Game Controllers",
      image: "/images/p4.jpg",
      price: 250,
      countInStock: 15,
      brand: "Xbox",
      rating: 4.5,
      numReviews: 14,
      description: "Controller for the Xbox One X/S",
    },
    {
      _id: "5",
      name: "White PS5 Controller",
      category: "Game Controller",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Playstation",
      rating: 4.5,
      numReviews: 10,
      description: "Controller for the PS5",
    },
    {
      _id: "6",
      name: "Neon Yellow/Blue Nintendo Switch Controller",
      category: "Game Controller",
      image: "/images/p6.jpg",
      price: 70,
      countInStock: 12,
      brand: "Nintendo",
      rating: 4.7,
      numReviews: 15,
      description: "Controller for the Nintendo Switch",
    },
  ],
};
export default data;
